"""A client for the agentplane operator API, version 0.46.0.

Generated by `tools/gen_operator_client.py` from the published OpenAPI document
(`openapi.json`); do not edit. Copy this file into your tooling and regenerate it
when you move to another version: the document is outside the compatibility
promise, so a client is only as current as the version it was generated from.

    from agentplane_operator import Client, OperatorError

    plane = Client("http://127.0.0.1:8081", token="...")
    for run in plane.list_runs()["runs"]:
        print(run)

Every method returns the parsed JSON answer (`None` for an answer with no body)
and raises `OperatorError` with the status and the `error` sentence for every
non-success answer, a redirect included: the client follows none. The tenant comes from the token, never from an argument.

Standard library only.
"""

from __future__ import annotations

import json
import urllib.error
import urllib.parse
import urllib.request
from typing import Any

API_VERSION = "0.46.0"


class OperatorError(Exception):
    """A non-success answer: its HTTP status and the API's `error` sentence."""

    def __init__(self, status: int, error: str) -> None:
        super().__init__(f"{status}: {error}")
        self.status = status
        self.error = error


class _NoRedirects(urllib.request.HTTPRedirectHandler):
    """Refuse every redirect.

    Followed, a POST answered 301, 302 or 303 is re-sent as a GET — a halt
    placed becomes a halt listing that answers 200 — and the token goes to
    whatever host the redirect names.
    """

    def redirect_request(self, req, fp, code, msg, headers, newurl):  # noqa: ANN001, ARG002
        fp.close()
        raise OperatorError(code, f"redirected to {newurl}; this client follows no redirect")


_OPENER = urllib.request.build_opener(_NoRedirects)


class Client:
    """The operator API of one plane, as the holder of one token."""

    def __init__(self, base_url: str, token: str | None = None, timeout: float = 30.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.token = token
        self.timeout = timeout

    def _call(
        self,
        method: str,
        path: str,
        query: dict[str, Any] | None = None,
        body: Any = None,
    ) -> Any:
        url = self.base_url + path
        present = {k: v for k, v in (query or {}).items() if v is not None}
        if present:
            url += "?" + urllib.parse.urlencode(present)
        headers = {"accept": "application/json"}
        if self.token is not None:
            headers["authorization"] = f"Bearer {self.token}"
        data = None
        if body is not None:
            data = json.dumps(body).encode("utf-8")
            headers["content-type"] = "application/json"
        request = urllib.request.Request(url, data=data, method=method, headers=headers)
        try:
            with _OPENER.open(request, timeout=self.timeout) as response:
                raw = response.read()
        except urllib.error.HTTPError as refused:
            raw = refused.read()
            try:
                error = json.loads(raw)["error"]
            except (ValueError, KeyError, TypeError):
                error = raw.decode("utf-8", "replace")
            raise OperatorError(refused.code, error) from None
        if not raw:
            return None
        return json.loads(raw)

    def attention(self) -> Any:
        """Every condition on this plane that needs a person, by name.

        GET /attention — policy action `api:attention`.
        Answers 200; raises OperatorError on 401, 403, 500.
        """
        return self._call("GET", "/attention")

    def list_cases(self, *, status: Any = None) -> Any:
        """Cases in a given state; escalated unless `status` names another.

        GET /cases — policy action `api:case.list`.
        Answers 200; raises OperatorError on 400, 401, 403, 500, 501.
        """
        return self._call("GET", "/cases", query={"status": status})

    def get_case(self, case: str) -> Any:
        """One case, its deadlines and its history.

        GET /cases/{case} — policy action `api:case.read`.
        Answers 200; raises OperatorError on 400, 401, 403, 404, 500, 501.
        """
        return self._call("GET", f"/cases/{_segment(case)}")

    def list_dead_letters(self) -> Any:
        """Messages that matched no waiter and aged out.

        GET /dead-letters — policy action `api:deadletter.list`.
        Answers 200; raises OperatorError on 401, 403, 500, 501.
        """
        return self._call("GET", "/dead-letters")

    def last_drill(self) -> Any:
        """When this plane last rehearsed recovery, and what it found.

        GET /drill — policy action `api:drill.read`.
        Answers 200; raises OperatorError on 401, 403, 404, 500.
        """
        return self._call("GET", "/drill")

    def deliver_event(self, body: dict[str, Any]) -> Any:
        """Deliver an inbound message to whichever run waits for it.

        POST /events — policy action `api:event.deliver`.
        Answers 200; raises OperatorError on 400, 401, 403, 409, 413, 500, 501, 503.
        """
        return self._call("POST", "/events", body=body)

    def list_halts(self, *, state: Any = None) -> Any:
        """Every halt standing now, and why; or the recorded lifts.

        GET /halts — policy action `api:halt.list`.
        Answers 200; raises OperatorError on 400, 401, 403, 500, 501.
        """
        return self._call("GET", "/halts", query={"state": state})

    def place_halt(self, body: dict[str, Any]) -> Any:
        """Throw the emergency stop for a scope, and answer how far it reaches.

        POST /halts — policy action `api:halt.place`.
        Answers 200; raises OperatorError on 400, 401, 403, 413, 415, 422, 500, 501.
        """
        return self._call("POST", "/halts", body=body)

    def lift_halt(self, body: dict[str, Any]) -> Any:
        """Lift a halt, and answer whether one was standing.

        POST /halts/lift — policy action `api:halt.lift`.
        Answers 200; raises OperatorError on 400, 401, 403, 413, 415, 422, 500, 501.
        """
        return self._call("POST", "/halts/lift", body=body)

    def list_holds(self, *, state: Any = None) -> Any:
        """Every matter preserved against erasure, oldest hold first; or the recorded releases.

        GET /holds — policy action `api:hold.list`.
        Answers 200; raises OperatorError on 400, 401, 403, 500, 501.
        """
        return self._call("GET", "/holds", query={"state": state})

    def place_hold(self, body: dict[str, Any]) -> Any:
        """Preserve one matter against every erasure verb.

        POST /holds — policy action `api:hold.place`.
        Answers 200; raises OperatorError on 400, 401, 403, 404, 413, 415, 422, 500, 501.
        """
        return self._call("POST", "/holds", body=body)

    def release_hold(self, body: dict[str, Any]) -> Any:
        """Lift a legal hold.

        POST /holds/release — policy action `api:hold.release`.
        Answers 200; raises OperatorError on 400, 401, 403, 404, 413, 415, 422, 500, 501.
        """
        return self._call("POST", "/holds/release", body=body)

    def list_breached_obligations(self) -> Any:
        """Missed obligations nobody has accounted for, longest overdue first.

        GET /obligations — policy action `api:obligation.list`.
        Answers 200; raises OperatorError on 401, 403, 500, 501.
        """
        return self._call("GET", "/obligations")

    def acknowledge_obligation(self, body: dict[str, Any]) -> Any:
        """Account for a missed obligation, taking it off the listing.

        POST /obligations/acknowledge — policy action `api:obligation.acknowledge`.
        Answers 200; raises OperatorError on 400, 401, 403, 404, 409, 413, 415, 422, 500, 501.
        """
        return self._call("POST", "/obligations/acknowledge", body=body)

    def list_parked_push(self) -> Any:
        """Webhook registrations a delivery worker gave up on.

        GET /push — policy action `api:push.list`.
        Served by a plane built with the `push` feature.
        Answers 200; raises OperatorError on 401, 403, 500, 501.
        """
        return self._call("GET", "/push")

    def rearm_push(self, body: dict[str, Any]) -> Any:
        """Re-arm a parked registration once its receiver answers again.

        POST /push/rearm — policy action `api:push.rearm`.
        Served by a plane built with the `push` feature.
        Answers 200; raises OperatorError on 400, 401, 403, 409, 413, 415, 422, 500, 501.
        """
        return self._call("POST", "/push/rearm", body=body)

    def list_runs(self, *, outcome: Any = None) -> Any:
        """Runs that ended a given way; quarantined unless `outcome` names another.

        GET /runs — policy action `api:run.list`.
        Answers 200; raises OperatorError on 400, 401, 403, 500.
        """
        return self._call("GET", "/runs", query={"outcome": outcome})

    def list_live_runs(self, *, subject: Any = None) -> Any:
        """Runs holding an admission slot now, each with its agent and subject.

        GET /runs/live — policy action `api:run.live`.
        Answers 200; raises OperatorError on 400, 401, 403, 500, 501.
        """
        return self._call("GET", "/runs/live", query={"subject": subject})

    def list_waiting_runs(self) -> Any:
        """Suspended runs and what each waits for, soonest due first.

        GET /runs/waiting — policy action `api:run.waiting`.
        Answers 200; raises OperatorError on 401, 403, 500.
        """
        return self._call("GET", "/runs/waiting")

    def get_run(self, run: str) -> Any:
        """One run: its status, why it is not finishing, and what is undecided.

        GET /runs/{run} — policy action `api:run.read`.
        Answers 200; raises OperatorError on 400, 401, 403, 404, 500.
        """
        return self._call("GET", f"/runs/{_segment(run)}")

    def abandon_run(self, run: str, body: dict[str, Any]) -> Any:
        """Close a quarantined run whose outcome will never be established.

        POST /runs/{run}/abandon — policy action `api:run.abandon`.
        Answers 200; raises OperatorError on 400, 401, 403, 404, 409, 413, 415, 422, 500.
        """
        return self._call("POST", f"/runs/{_segment(run)}/abandon", body=body)

    def cancel_run(self, run: str, body: dict[str, Any]) -> Any:
        """Stop a run at its next step boundary.

        POST /runs/{run}/cancel — policy action `api:run.cancel`.
        Answers 202; raises OperatorError on 400, 401, 403, 404, 409, 413, 415, 422, 500.
        """
        return self._call("POST", f"/runs/{_segment(run)}/cancel", body=body)

    def run_history(self, run: str, *, from_: Any = None) -> Any:
        """One run's journal, a page at a time from a sequence.

        GET /runs/{run}/history — policy action `api:run.history`.
        Answers 200; raises OperatorError on 400, 401, 403, 404, 500.
        """
        return self._call("GET", f"/runs/{_segment(run)}/history", query={"from": from_})

    def reconcile_effect(self, run: str, body: dict[str, Any]) -> Any:
        """Assert what happened to one effect the runtime could not decide.

        POST /runs/{run}/reconcile — policy action `api:effect.reconcile`.
        Answers 200; raises OperatorError on 400, 401, 403, 404, 409, 413, 415, 422, 500.
        """
        return self._call("POST", f"/runs/{_segment(run)}/reconcile", body=body)

    def reopen_run(self, run: str, body: dict[str, Any]) -> Any:
        """Hand a quarantined run back to the runtime, and answer what it reached.

        POST /runs/{run}/reopen — policy action `api:run.reopen`.
        Answers 200; raises OperatorError on 400, 401, 403, 404, 409, 413, 415, 422, 500.
        """
        return self._call("POST", f"/runs/{_segment(run)}/reopen", body=body)

    def list_tasks(self) -> Any:
        """The worklist the caller's roles entitle them to.

        GET /tasks — policy action `api:task.list`.
        Answers 200; raises OperatorError on 401, 403, 500, 501.
        """
        return self._call("GET", "/tasks")

    def get_task(self, task: str) -> Any:
        """One task, and whether this caller may decide it.

        GET /tasks/{task} — policy action `api:task.read`.
        Answers 200; raises OperatorError on 400, 401, 403, 404, 500, 501.
        """
        return self._call("GET", f"/tasks/{_segment(task)}")

    def claim_task(self, task: str) -> Any:
        """Reserve a task so no other reviewer works it.

        POST /tasks/{task}/claim — policy action `api:task.claim`.
        Answers 200; raises OperatorError on 400, 401, 403, 404, 409, 500, 501.
        """
        return self._call("POST", f"/tasks/{_segment(task)}/claim")

    def decide_task(self, task: str, body: dict[str, Any]) -> Any:
        """Approve or reject a task as the authenticated caller.

        POST /tasks/{task}/decide — policy action `api:task.decide`.
        Answers 200; raises OperatorError on 400, 401, 403, 404, 409, 412, 413, 415, 422, 500, 501.
        """
        return self._call("POST", f"/tasks/{_segment(task)}/decide", body=body)

    def release_task(self, task: str) -> Any:
        """Give a claimed task back without deciding it.

        POST /tasks/{task}/release — policy action `api:task.release`.
        Answers 204; raises OperatorError on 400, 401, 403, 404, 409, 500, 501.
        """
        return self._call("POST", f"/tasks/{_segment(task)}/release")

    def take_over_task(self, task: str, body: dict[str, Any]) -> Any:
        """Take a task over from the holder named in the body.

        POST /tasks/{task}/takeover — policy action `api:task.takeover`.
        Answers 200; raises OperatorError on 400, 401, 403, 404, 409, 413, 415, 422, 500, 501.
        """
        return self._call("POST", f"/tasks/{_segment(task)}/takeover", body=body)


def _segment(value: str) -> str:
    return urllib.parse.quote(str(value), safe="")
