#!/usr/bin/env python3
"""Generate the Python operator client from the published OpenAPI document.

Reads `site/static/openapi.json` and nothing else — no Rust, no route list of
its own — so a client that works is evidence the document is enough to build
one from. Writes `clients/python/agentplane_operator.py`.

    python3 tools/gen_operator_client.py              write the client
    python3 tools/gen_operator_client.py --check      exit 1 if the committed client is stale
    python3 tools/gen_operator_client.py --self-test  prove the output follows the document

The generated client is one standard-library module: a `Client` with one method
per operation, returning the parsed JSON answer and raising `OperatorError`
for every non-success answer. It calls the operator API and nothing else.

Standard library only, like the client it writes.
"""

from __future__ import annotations

import ast
import copy
import http.server
import json
import keyword
import pathlib
import sys
import threading
import types

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCUMENT = ROOT / "site" / "static" / "openapi.json"
CLIENT = ROOT / "clients" / "python" / "agentplane_operator.py"
REGENERATE = "python3 tools/gen_operator_client.py"

HEADER = '''"""A client for the agentplane operator API, version {version}.

Generated by `tools/gen_operator_client.py` from the published OpenAPI document
(`openapi.json`); do not edit. Copy this file into your tooling and regenerate it
when you move to another version: the document is outside the compatibility
promise, so a client is only as current as the version it was generated from.

    from agentplane_operator import Client, OperatorError

    plane = Client("http://127.0.0.1:8081", token="...")
    for run in plane.list_runs()["runs"]:
        print(run)

Every method returns the parsed JSON answer (`None` for an answer with no body)
and raises `OperatorError` with the status and the `error` sentence for every
non-success answer, a redirect included: the client follows none. The tenant comes from the token, never from an argument.

Standard library only.
"""

from __future__ import annotations

import json
import urllib.error
import urllib.parse
import urllib.request
from typing import Any

API_VERSION = "{version}"


class OperatorError(Exception):
    """A non-success answer: its HTTP status and the API's `error` sentence."""

    def __init__(self, status: int, error: str) -> None:
        super().__init__(f"{{status}}: {{error}}")
        self.status = status
        self.error = error


class _NoRedirects(urllib.request.HTTPRedirectHandler):
    """Refuse every redirect.

    Followed, a POST answered 301, 302 or 303 is re-sent as a GET — a halt
    placed becomes a halt listing that answers 200 — and the token goes to
    whatever host the redirect names.
    """

    def redirect_request(self, req, fp, code, msg, headers, newurl):  # noqa: ANN001, ARG002
        fp.close()
        raise OperatorError(code, f"redirected to {{newurl}}; this client follows no redirect")


_OPENER = urllib.request.build_opener(_NoRedirects)


class Client:
    """The operator API of one plane, as the holder of one token."""

    def __init__(self, base_url: str, token: str | None = None, timeout: float = 30.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.token = token
        self.timeout = timeout

    def _call(
        self,
        method: str,
        path: str,
        query: dict[str, Any] | None = None,
        body: Any = None,
    ) -> Any:
        url = self.base_url + path
        present = {{k: v for k, v in (query or {{}}).items() if v is not None}}
        if present:
            url += "?" + urllib.parse.urlencode(present)
        headers = {{"accept": "application/json"}}
        if self.token is not None:
            headers["authorization"] = f"Bearer {{self.token}}"
        data = None
        if body is not None:
            data = json.dumps(body).encode("utf-8")
            headers["content-type"] = "application/json"
        request = urllib.request.Request(url, data=data, method=method, headers=headers)
        try:
            with _OPENER.open(request, timeout=self.timeout) as response:
                raw = response.read()
        except urllib.error.HTTPError as refused:
            raw = refused.read()
            try:
                error = json.loads(raw)["error"]
            except (ValueError, KeyError, TypeError):
                error = raw.decode("utf-8", "replace")
            raise OperatorError(refused.code, error) from None
        if not raw:
            return None
        return json.loads(raw)


def _segment(value: str) -> str:
    return urllib.parse.quote(str(value), safe="")
'''

METHOD_ORDER = {"get": 0, "post": 1, "put": 2, "patch": 3, "delete": 4}


def identifier(name: str) -> str:
    name = name.replace("-", "_")
    return name + "_" if keyword.iskeyword(name) else name


def operations(document: dict) -> list[tuple[str, str, dict]]:
    found = []
    for path in sorted(document.get("paths", {})):
        for method, operation in document["paths"][path].items():
            if method in METHOD_ORDER:
                found.append((path, method, operation))
    found.sort(key=lambda o: (o[0], METHOD_ORDER[o[1]]))
    return found


def method_source(path: str, method: str, operation: dict) -> str:
    name = identifier(operation["operationId"])
    parameters = operation.get("parameters", [])
    in_path = [p["name"] for p in parameters if p["in"] == "path"]
    in_query = [p for p in parameters if p["in"] == "query"]
    has_body = "requestBody" in operation

    arguments = ["self"] + [f"{identifier(p)}: str" for p in in_path]
    if has_body:
        arguments.append("body: dict[str, Any]")
    required_query = [p for p in in_query if p.get("required")]
    optional_query = [p for p in in_query if not p.get("required")]
    keyword_only = [f"{identifier(p['name'])}: Any" for p in required_query]
    keyword_only += [f"{identifier(p['name'])}: Any = None" for p in optional_query]
    if keyword_only:
        arguments.append("*")
        arguments.extend(keyword_only)

    url = path
    for p in in_path:
        url = url.replace("{" + p + "}", "{_segment(" + identifier(p) + ")}")
    url_expr = f'f"{url}"' if in_path else f'"{url}"'

    success = sorted(s for s in operation["responses"] if s.startswith("2"))
    refusals = sorted(s for s in operation["responses"] if not s.startswith("2"))
    doc = [operation.get("summary", "").strip()]
    doc.append("")
    doc.append(f"{method.upper()} {path} — policy action `{operation.get('x-agentplane-action', '')}`.")
    if "x-agentplane-feature" in operation:
        doc.append(f"Served by a plane built with the `{operation['x-agentplane-feature']}` feature.")
    doc.append(f"Answers {', '.join(success)}; raises OperatorError on {', '.join(refusals)}.")

    call = [f'"{method.upper()}"', url_expr]
    if in_query:
        pairs = ", ".join(f'"{p["name"]}": {identifier(p["name"])}' for p in in_query)
        call.append(f"query={{{pairs}}}")
    if has_body:
        call.append("body=body")

    lines = [f"    def {name}({', '.join(arguments)}) -> Any:"]
    lines.append('        """' + doc[0])
    lines.extend(("        " + d) if d else "" for d in doc[1:])
    lines.append('        """')
    lines.append(f"        return self._call({', '.join(call)})")
    return "\n".join(lines)


def generate(document: dict) -> str:
    version = document["info"]["version"]
    methods = [method_source(*op) for op in operations(document)]
    # The helper sits after the class in the header; methods go inside the class.
    head, helper = HEADER.format(version=version).split("\n\ndef _segment", 1)
    return head.rstrip("\n") + "\n\n" + "\n\n".join(methods) + "\n\n\ndef _segment" + helper


def load() -> dict:
    return json.loads(DOCUMENT.read_text(encoding="utf-8"))


def check() -> int:
    wanted = generate(load())
    committed = CLIENT.read_text(encoding="utf-8") if CLIENT.exists() else ""
    if wanted != committed:
        print(f"{CLIENT.relative_to(ROOT)} is not what the published document generates — run `{REGENERATE}`")
        return 1
    print(f"{CLIENT.relative_to(ROOT)} matches {DOCUMENT.relative_to(ROOT)}")
    return 0


def defined_names(tree: ast.AST) -> set[str]:
    names = set()
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            names.add(node.name)
        elif isinstance(node, ast.arg):
            names.add(node.arg)
        elif isinstance(node, ast.Name) and isinstance(node.ctx, ast.Store):
            names.add(node.id)
        elif isinstance(node, ast.Attribute) and isinstance(node.ctx, ast.Store):
            names.add(node.attr)
    return names


def imported_modules(tree: ast.AST) -> set[str]:
    modules = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            modules.update(alias.name.split(".")[0] for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            modules.add((node.module or "").split(".")[0])
    return modules


def redirect_failures(source: str) -> list[str]:
    """Run the generated client against a server that answers every write with
    a redirect, and report each one it followed."""
    module = types.ModuleType("agentplane_operator")
    exec(compile(source, "agentplane_operator.py", "exec"), module.__dict__)  # noqa: S102
    seen: list[tuple[str, str, str | None]] = []
    code = [0]

    class Redirecting(http.server.BaseHTTPRequestHandler):
        def log_message(self, *_: object) -> None:
            pass

        def _answer(self) -> None:
            seen.append((self.command, self.path, self.headers.get("authorization")))
            if self.path == "/halts":
                self.send_response(code[0])
                self.send_header("location", "/elsewhere")
                self.send_header("content-length", "0")
                self.end_headers()
                return
            body = b'{"halts": []}'
            self.send_response(200)
            self.send_header("content-type", "application/json")
            self.send_header("content-length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        do_GET = do_POST = _answer  # noqa: N815

    server = http.server.HTTPServer(("127.0.0.1", 0), Redirecting)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    failures = []
    try:
        plane = module.Client(f"http://127.0.0.1:{server.server_address[1]}", token="secret")
        for status in (301, 302, 303, 307, 308):
            code[0] = status
            seen.clear()
            try:
                answer = plane.place_halt({"scope": "tenant", "reason": "self-test"})
            except module.OperatorError as refused:
                if refused.status != status:
                    failures.append(f"a {status} redirect raised status {refused.status}")
            else:
                failures.append(f"a POST answered {status} returned {answer!r} instead of raising")
            onward = [s for s in seen if s[1] != "/halts"]
            if onward:
                failures.append(f"a {status} redirect was followed: {onward}")
    finally:
        server.shutdown()
        server.server_close()
    return failures


def self_test() -> int:
    failures = []
    document = load()
    baseline = generate(document)

    tree = ast.parse(baseline)
    outside = {m for m in imported_modules(tree) if m not in sys.stdlib_module_names}
    if outside:
        failures.append(f"the client imports outside the standard library: {sorted(outside)}")
    skill = sorted(n for n in defined_names(tree) if "skill" in n.lower())
    if skill:
        failures.append(f"the client defines a name about skills: {skill}")
    for path, method, operation in operations(document):
        if f"    def {identifier(operation['operationId'])}(" not in baseline:
            failures.append(f"{method.upper()} {path} has no method")

    added = copy.deepcopy(document)
    added["paths"]["/self-test"] = {
        "get": {
            "operationId": "self_test_probe",
            "summary": "A probe.",
            "responses": {"200": {"description": "The answer."}},
        }
    }
    if generate(added) == baseline or "def self_test_probe(" not in generate(added):
        failures.append("adding an operation to the document did not change the client")

    removed = copy.deepcopy(document)
    first_path = sorted(removed["paths"])[0]
    del removed["paths"][first_path]
    if generate(removed) == baseline:
        failures.append("removing an operation from the document did not change the client")

    failures.extend(redirect_failures(baseline))

    for failure in failures:
        print(f"self-test: {failure}")
    if failures:
        return 1
    print(
        "self-test: the client follows the document, imports only the standard library, "
        "names no skill, and follows no redirect"
    )
    return 0


def main(argv: list[str]) -> int:
    if argv == ["--check"]:
        return check()
    if argv == ["--self-test"]:
        return self_test()
    if argv:
        print(__doc__.strip().splitlines()[0])
        print("usage: gen_operator_client.py [--check | --self-test]")
        return 2
    CLIENT.parent.mkdir(parents=True, exist_ok=True)
    CLIENT.write_text(generate(load()), encoding="utf-8")
    print(f"wrote {CLIENT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
